### ISSUE TITLE
installing without xgboost

### ISSUE THREAD

**Issue by StatHans** [JacekBialek/PriceIndices#7]
Is there any way to install this package without including xgboost?

Your code would be very useful for us, but due to the C++ compiler on our R server we cannot install the xgboost library which is required for PriceIndices.

How could i get past this assuming i cannot update the C++ compiler according to the needs of xgboost?

**Comment by JacekBialek** [comment]
Hi, 
you can try to download all package files from GitHub, remove "xgboost" from 'Imports' Section in the Description file and then install the package manually, i.e. by using 'devtools'. It should work. If you need my help with it please give me a note.
Best regards, 
Jacek.

**Comment by JacekBialek** [comment]
Before that, you could also try installing my package using the following instruction: 
install.packages("PriceIndices", method = "wininet", dependencies =FALSE)

**Comment by StatHans** [comment]
Thanks! The structure of the code makes it quite easy to exclude the xgboost section or to just get the functions we need.
